from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
import hashlib
import json
import threading
from typing import Any

from sqlalchemy import MetaData, Table, create_engine
from sqlalchemy.engine import Engine

from db2api_service.config import Settings


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _is_autogenerated(column: Any) -> bool:
    if getattr(column, "computed", None) is not None:
        return True
    if getattr(column, "identity", None) is not None:
        return True
    return column.autoincrement in (True, "auto")


@dataclass(frozen=True)
class ColumnDescriptor:
    name: str
    type_name: str
    nullable: bool
    primary_key: bool
    has_default: bool
    autogenerated: bool
    python_type: type[Any] | None = field(default=None, repr=False, compare=False)

    @property
    def python_type_name(self) -> str | None:
        return None if self.python_type is None else self.python_type.__name__

    def to_summary(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "type": self.type_name,
            "nullable": self.nullable,
            "primary_key": self.primary_key,
            "has_default": self.has_default,
            "autogenerated": self.autogenerated,
            "python_type": self.python_type_name,
        }

    @classmethod
    def from_column(cls, column: Any) -> "ColumnDescriptor":
        python_type: type[Any] | None = None
        try:
            python_type = column.type.python_type
        except (AttributeError, NotImplementedError):
            python_type = None

        has_default = any(
            [
                column.default is not None,
                column.server_default is not None,
                getattr(column, "computed", None) is not None,
                getattr(column, "identity", None) is not None,
                column.autoincrement in (True, "auto"),
            ]
        )

        return cls(
            name=column.name,
            type_name=str(column.type),
            nullable=column.nullable,
            primary_key=column.primary_key,
            has_default=has_default,
            autogenerated=_is_autogenerated(column),
            python_type=python_type,
        )


@dataclass(frozen=True)
class TableDescriptor:
    name: str
    full_name: str
    primary_keys: tuple[str, ...]
    required_on_create: tuple[str, ...]
    writable_columns: tuple[str, ...]
    updatable_columns: tuple[str, ...]
    columns: dict[str, ColumnDescriptor]
    table: Table = field(repr=False, compare=False)

    @property
    def supports_identity(self) -> bool:
        return bool(self.primary_keys)

    def to_summary(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "full_name": self.full_name,
            "primary_keys": list(self.primary_keys),
            "required_on_create": list(self.required_on_create),
            "writable_columns": list(self.writable_columns),
            "updatable_columns": list(self.updatable_columns),
            "supports_identity": self.supports_identity,
            "columns": {
                column_name: descriptor.to_summary()
                for column_name, descriptor in self.columns.items()
            },
        }

    def signature(self) -> dict[str, Any]:
        return {
            "primary_keys": list(self.primary_keys),
            "required_on_create": list(self.required_on_create),
            "writable_columns": list(self.writable_columns),
            "updatable_columns": list(self.updatable_columns),
            "columns": {
                column_name: descriptor.to_summary()
                for column_name, descriptor in self.columns.items()
            },
        }

    @classmethod
    def from_table(cls, table: Table) -> "TableDescriptor":
        columns = {
            column.name: ColumnDescriptor.from_column(column)
            for column in table.columns
        }

        primary_keys = tuple(column.name for column in table.primary_key.columns)
        writable_columns = tuple(
            column.name
            for column in table.columns
            if getattr(column, "computed", None) is None
        )
        updatable_columns = tuple(
            column_name
            for column_name in writable_columns
            if column_name not in primary_keys
        )
        required_on_create = tuple(
            column.name
            for column in table.columns
            if not column.nullable
            and column.name in writable_columns
            and not columns[column.name].has_default
        )

        return cls(
            name=table.name,
            full_name=table.fullname,
            primary_keys=primary_keys,
            required_on_create=required_on_create,
            writable_columns=writable_columns,
            updatable_columns=updatable_columns,
            columns=columns,
            table=table,
        )


@dataclass(frozen=True)
class RegistrySnapshot:
    refreshed_at: datetime
    digest: str
    tables: dict[str, TableDescriptor]

    def to_summary(self) -> dict[str, Any]:
        return {
            "refreshed_at": self.refreshed_at.isoformat(),
            "schema_digest": self.digest,
            "table_count": len(self.tables),
            "tables": {
                table_name: descriptor.to_summary()
                for table_name, descriptor in self.tables.items()
            },
        }


@dataclass(frozen=True)
class DatabaseDescriptor:
    dialect: str
    drivername: str
    dbapi_driver: str
    schema_name: str | None

    def to_summary(self) -> dict[str, Any]:
        return {
            "dialect": self.dialect,
            "drivername": self.drivername,
            "dbapi_driver": self.dbapi_driver,
            "schema_name": self.schema_name,
        }


class SchemaRegistry:
    def __init__(self, settings: Settings) -> None:
        self.settings = settings
        self.engine: Engine = create_engine(settings.database_url, future=True)
        self._lock = threading.RLock()
        self._refresh_interval = timedelta(
            seconds=settings.schema_refresh_interval_seconds
        )
        self._snapshot = RegistrySnapshot(
            refreshed_at=datetime.fromtimestamp(0, timezone.utc),
            digest="",
            tables={},
        )

    def dispose(self) -> None:
        self.engine.dispose()

    def describe_database(self) -> DatabaseDescriptor:
        return DatabaseDescriptor(
            dialect=self.engine.dialect.name,
            drivername=self.engine.url.drivername,
            dbapi_driver=self.engine.dialect.driver,
            schema_name=self.settings.schema_name,
        )

    def snapshot(self) -> RegistrySnapshot:
        with self._lock:
            return self._snapshot

    def refresh_if_stale(self) -> RegistrySnapshot:
        with self._lock:
            snapshot = self._snapshot
            stale = (
                not snapshot.tables
                or _utcnow() - snapshot.refreshed_at >= self._refresh_interval
            )

        if stale:
            return self.refresh(force=True)
        return snapshot

    def refresh(self, force: bool = False) -> RegistrySnapshot:
        if not force:
            return self.refresh_if_stale()

        metadata = MetaData(schema=self.settings.schema_name)
        reflect_kwargs: dict[str, Any] = {"views": False}
        if self.settings.include_tables:
            reflect_kwargs["only"] = sorted(self.settings.include_tables)

        metadata.reflect(
            bind=self.engine,
            schema=self.settings.schema_name,
            **reflect_kwargs,
        )

        tables = {
            table.name: TableDescriptor.from_table(table)
            for table in metadata.sorted_tables
            if table.name not in set(self.settings.exclude_tables)
        }

        digest_payload = {
            table_name: descriptor.signature()
            for table_name, descriptor in tables.items()
        }
        digest = hashlib.sha256(
            json.dumps(digest_payload, sort_keys=True, separators=(",", ":")).encode(
                "utf-8"
            )
        ).hexdigest()

        snapshot = RegistrySnapshot(
            refreshed_at=_utcnow(),
            digest=digest,
            tables=tables,
        )

        with self._lock:
            self._snapshot = snapshot

        return snapshot

    def get_table(
        self,
        table_name: str,
        *,
        force_refresh: bool = False,
    ) -> TableDescriptor | None:
        snapshot = self.refresh(force=True) if force_refresh else self.refresh_if_stale()
        return snapshot.tables.get(table_name)
